### PR TITLE
Challenge 7

### PR DESCRIPTION
**Pull request by benesjan**
I really enjoy these challenges and Foundry so I decided to reimplement more of the tests. I might add more levels in the next few days if I find the time.

### CODE REVIEW

**Comment by nicolasgarcia214** [comment]
Hi @benesjan!
Thanks for contributing but I already had the challenge ready but I hadn't pushed it. 😅
Look at the commit date.

I'm glad you want to help me with the others. I haven't had time to code them.

image

**Comment by nicolasgarcia214** [comment]
Let me know which ones you want to do and I'll work on the others. @benesjan

**Comment by benesjan** [comment]
> Hi @benesjan! Thanks for contributing but I already had the challenge ready but I hadn't pushed it. 😅 Look at the commit date.
> 
> I'm glad you want to help me with the others. I haven't had time to code them.
> 
> image

Not asking was very smart from me 🤦‍♂️

Have you done anything on challenge 8 already?

**Comment by nicolasgarcia214** [comment]
I'm on it right now 💪
From 9 to 12 I have nothing yet.

**Comment by benesjan** [comment]
> > I'm on it right now 💪 From 9 to 12 I have nothing yet.
> 
> Ok, I will try to do challenge 9 today 👍

Some unexpected work came to it and I didn't manage to progress. Sorry

**Pull request closed without merging**
